version: '3.8'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns
    environment:
      API_KEY: ${API_KEY}
      ZONE: ${ZONE}
      SUBDOMAIN: ${SUBDOMAIN}
      PROXIED: true
      TTL: 1
      DELETE_ON_STOP: false
      TZ: Asia/Kolkata
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

